### ISSUE TITLE
Handle special cases

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/FcgR.jl#103]
- [x] blood/bone have concentrations
- [x] blood/bone should pass through C1q affinities to deal with complement
- [x] HIV should pass through neutralizing activity quantity

https://github.com/meyer-lab/FcgR.jl/blob/c37d0d41716b8f10b3a86bb6319ce4a29a2b1f7b/src/figures/figureW.jl#L22

**Comment by cyrillustan** [comment]
Can this be a potential problem: FcRs on a cell type are competing against receptors on other cell types for the same pool of IgGs, but we simply calculated the effect of each cell type separately as if no other FcRs exist and put the numbers together?
