### ISSUE TITLE
Binding model methods description

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/FcgR.jl#127]
It's probably a good time to write a methods section describing the multi-ligand multi-receptor multivalent binding model. This can get reused verbatim in the depletion, translation and cell selectivity manuscripts. Starting with the text in Robinett et al might be helpful, too.

**Comment by cyrillustan** [comment]
Question: what would happen if an IC is bound to an activating receptor and an inhibitory receptor simultaneously?

**Comment by aarmey** [comment]
Currently, we just take the additive combination (# activating receptors - # inhibitory receptors), just like in Robinett. However, it's certainly possible that receptors have distinct activities, or more complex effects, especially between activating and inhibitory receptors. The Georgiou lab is collecting data that might help answer this, or we also proposed in the grant to do *in vitro* ADCC/ADCP assays, which might allow us to fit receptor activities.
