### ISSUE TITLE
ImportRtot gives different receptor counts than what was hardcoded on Python

### ISSUE THREAD

**Issue by stephendl102** [meyer-lab/FcgR.jl#70]
On Julia: in plotIsobologramTwo(), FcExpr = importRtot(murine = true)[:, 2] 
FcExpr is equal to [2571.328120206041 12885.868960926426  12563.48061974062 501.12724995869615]
For plotIsobologramTwo() on the old version, we had FcExpr = np.array([2571.0, 12886.0, 12563.0, 2371.0]) 
The actual data file was the same, so it was either miscoded on the old repository, or importRtot() got one value different...
@aarmey

**Comment by aarmey** [comment]
Ok, I'm guessing that was an error in Python. That would explain differences you see.
