### ISSUE TITLE
Make sure that we are using the most recent mouse and human receptor profiling

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/FcgR.jl#79]
Markus sent a link to his new dataset. Should be posted on Slack.

**Comment by robthemike1** [comment]
I have the new data sets uploaded and the import appears to be working fine. The only change to the data after our meeting yesterday is the addition of a FcgRIIC receptor for each human cell type with abundance set to zero. The only issue is I can't figure out exactly why the numerical solver is failing.

**Comment by aarmey** [comment]
Open a PR? I'll look at it though there.
