### ISSUE TITLE
Project measurements through binding model

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/FcgR.jl#89]
To look at clustering of HIV vaccine trials

**Comment by aarmey** [comment]
@murphymadeleine21 the last data import we should do before setting up the model is the following. Let me know if I can clarify this further...

![IMG_0186](https://user-images.githubusercontent.com/2065146/76716447-6e2dd080-66ed-11ea-96fb-fcd9bd502c23.png)

**Comment by murphymadeleine21** [comment]
FcgRIIa, FcgRIIIa, and FcgRIIIb all have two subsets of data (The different signals, I believe? For example FcgRIIIa.**F158**.6H.HIV1.p66 vs FcgRIIIa.**V158**.6H.HIV1.p66). Do you want each subset in a separate column? Or only one column for each receptor? If we use 1 column for each one, I'm not sure how we would differentiate between the different subsets.

**Comment by aarmey** [comment]
You can consider those separate receptors. They are genetic variants with differing affinities.
